config/routes.rb
Rails.application.routes.draw do
  resources :service_song_types
  resources :specials
  resources :singers
  resources :service_songs
  resources :services
  resources :service_types
  resources :songs
  resources :hymn_books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :service_type

  has_many :service_songs
  has_many :songs, through: :service_songs
  has_many :specials
  
  def label
    "#{service_type.name} - #{date}"
  end
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @showing_all = params.key?(:all)
    if params[:all]
      @services = Service.all
    else
      @services = Service.where('date >= ?', Date.current)
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @edit_mode = params.key?(:edit)
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:date, :service_type_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= bootstrap_form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.date_select :date %>
  <%= form.collection_select :service_type_id, ServiceType.all, :id, :name, prompt: true %>
  <%= form.submit %>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Services</h1>

<% if @showing_all %>
  <%= link_to 'Show Future', services_path %>
<% else %>
  <%= link_to 'Show All', services_path(all: true) %>
<% end %>
<p></p>
<p></p>
<table>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.label, service %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<h1><%= @service.service_type.name %> - <%= @service.date %></h1>

<%= link_to 'Edit', edit_service_path(@service), class: 'btn btn-outline-primary btn-sm' %>
<%= link_to 'Delete', service_path(@service), method: :delete, class: 'btn btn-outline-danger btn-sm', confirm: 'Are you sure you want to delete this service?' %>
<hr />
<div class='row'>
  <div class='col col-xs-12 col-md-6'>
    <h2>Songs <%= link_to '+', new_service_song_path(service_id: @service.id) %></h2>
    <% if @edit_mode %>
      <p>
        <%= link_to 'Exit Edit Mode', service_path(@service) %>
      </p>
    <% else %>
      <p>
        <%= link_to 'Edit Mode', service_path(@service, edit: true) %>
      </p>
    <% end %>
    <table class='table'>
      <thead>
        <tr>
          <th>Page</th>
          <th>Book</th>
          <th>Name</th>
          <th>Type</th>
          <% if @edit_mode %>
            <th>Edit</th>
            <th>Delete</th>
          <% end %>
        </tr>
      </thead>
      <% if @edit_mode %>
        <tbody>
      <% else %>
        <tbody class="sortable">
      <% end %>
        <% @service.service_songs.order(:sort).each_with_sortable_id do |item, sortable_id| %>
          <%= link_to [:edit, item] do %>
            <tr id="<%= sortable_id %>">  <!-- Needs id tag on sorting elements -->
              <td><%= item.song.page_number %></td>
              <td><%= item.song.hymn_book.name %></td>
              <td><%= item.song.name %></td>
              <td><%= item.service_song_type.name %></td>
              <% if @edit_mode %>
                <td><%= link_to 'Edit', [:edit, item] %></td>
                <td><%= link_to 'Delete', item, data: { confirm: 'Are you sure?' }, method: :delete %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class='col col-xs-12 col-md-6'>
    <h2>Specials <%= link_to '+', new_special_path %></h2>
    <ul>
      <% @service.specials.each do |special| %>
        <li>
          <%= special.singer.full_name %>
        </li>
      <% end %>
    </ul>
  </div>
</div>