config/routes.rb
Rails.application.routes.draw do
  resources :service_song_types
  resources :specials
  resources :singers
  resources :service_songs
  resources :services
  resources :service_types
  resources :songs
  resources :hymn_books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/singer.rb
class Singer < ApplicationRecord
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: [:show, :edit, :update, :destroy]

  # GET /singers
  # GET /singers.json
  def index
    @singers = Singer.all
  end

  # GET /singers/1
  # GET /singers/1.json
  def show
  end

  # GET /singers/new
  def new
    @singer = Singer.new
  end

  # GET /singers/1/edit
  def edit
  end

  # POST /singers
  # POST /singers.json
  def create
    @singer = Singer.new(singer_params)

    respond_to do |format|
      if @singer.save
        format.html { redirect_to @singer, notice: 'Singer was successfully created.' }
        format.json { render :show, status: :created, location: @singer }
      else
        format.html { render :new }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singers/1
  # PATCH/PUT /singers/1.json
  def update
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to @singer, notice: 'Singer was successfully updated.' }
        format.json { render :show, status: :ok, location: @singer }
      else
        format.html { render :edit }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1
  # DELETE /singers/1.json
  def destroy
    @singer.destroy
    respond_to do |format|
      format.html { redirect_to singers_url, notice: 'Singer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @singer = Singer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def singer_params
      params.require(:singer).permit(:first_name, :last_name)
    end
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/views/singers/_form.html.erb
<%= bootstrap_form_with(model: singer, local: true) do |form| %>
  <% if singer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
      <% singer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  <%= form.submit %>
<% end %>

app/views/singers/edit.html.erb
<h1>Editing Singer</h1>

<%= render 'form', singer: @singer %>

<%= link_to 'Show', @singer %> |
<%= link_to 'Back', singers_path %>

app/views/singers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Singers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @singers.each do |singer| %>
      <tr>
        <td><%= singer.first_name %></td>
        <td><%= singer.last_name %></td>
        <td><%= link_to 'Show', singer %></td>
        <td><%= link_to 'Edit', edit_singer_path(singer) %></td>
        <td><%= link_to 'Destroy', singer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Singer', new_singer_path %>

app/views/singers/new.html.erb
<h1>New Singer</h1>

<%= render 'form', singer: @singer %>

<%= link_to 'Back', singers_path %>

app/views/singers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @singer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @singer.last_name %>
</p>

<%= link_to 'Edit', edit_singer_path(@singer) %> |
<%= link_to 'Back', singers_path %>