config/routes.rb
Rails.application.routes.draw do
  resources :service_song_types
  resources :specials
  resources :singers
  resources :service_songs
  resources :services
  resources :service_types
  resources :songs
  resources :hymn_books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hymn_book.rb
class HymnBook < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :service_type

  has_many :service_songs
  has_many :songs, through: :service_songs
  has_many :specials
  
  def label
    "#{service_type.name} - #{date}"
  end
end

app/models/service_song.rb
class ServiceSong < ApplicationRecord
  belongs_to :service
  belongs_to :song
  belongs_to :service_song_type

  include RailsSortable::Model
  set_sortable :sort
end

app/models/service_song_type.rb
class ServiceSongType < ApplicationRecord
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
end

app/models/singer.rb
class Singer < ApplicationRecord
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :hymn_book
  validates :page_number, uniqueness: { scope: :hymn_book }
end

app/models/special.rb
class Special < ApplicationRecord
  belongs_to :service
  belongs_to :singer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/service_song_types_controller.rb
class ServiceSongTypesController < ApplicationController
  before_action :set_service_song_type, only: [:show, :edit, :update, :destroy]

  # GET /service_song_types
  # GET /service_song_types.json
  def index
    @service_song_types = ServiceSongType.all
  end

  # GET /service_song_types/1
  # GET /service_song_types/1.json
  def show
  end

  # GET /service_song_types/new
  def new
    @service_song_type = ServiceSongType.new
  end

  # GET /service_song_types/1/edit
  def edit
  end

  # POST /service_song_types
  # POST /service_song_types.json
  def create
    @service_song_type = ServiceSongType.new(service_song_type_params)

    respond_to do |format|
      if @service_song_type.save
        format.html { redirect_to @service_song_type, notice: 'Service song type was successfully created.' }
        format.json { render :show, status: :created, location: @service_song_type }
      else
        format.html { render :new }
        format.json { render json: @service_song_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_song_types/1
  # PATCH/PUT /service_song_types/1.json
  def update
    respond_to do |format|
      if @service_song_type.update(service_song_type_params)
        format.html { redirect_to @service_song_type, notice: 'Service song type was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_song_type }
      else
        format.html { render :edit }
        format.json { render json: @service_song_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_song_types/1
  # DELETE /service_song_types/1.json
  def destroy
    @service_song_type.destroy
    respond_to do |format|
      format.html { redirect_to service_song_types_url, notice: 'Service song type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_song_type
      @service_song_type = ServiceSongType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_song_type_params
      params.require(:service_song_type).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order(:page_number).all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :page_number, :hymn_book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hymn_books_helper.rb
module HymnBooksHelper
end

app/helpers/service_song_types_helper.rb
module ServiceSongTypesHelper
end

app/helpers/service_songs_helper.rb
module ServiceSongsHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/service_song_types/_form.html.erb
<%= bootstrap_form_with(model: service_song_type, local: true) do |form| %>
  <% if service_song_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_song_type.errors.count, "error") %> prohibited this service_song_type from being saved:</h2>

      <ul>
      <% service_song_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/service_song_types/edit.html.erb
<h1>Editing Service Song Type</h1>

<%= render 'form', service_song_type: @service_song_type %>

<%= link_to 'Show', @service_song_type %> |
<%= link_to 'Back', service_song_types_path %>

app/views/service_song_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Song Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_song_types.each do |service_song_type| %>
      <tr>
        <td><%= service_song_type.name %></td>
        <td><%= link_to 'Show', service_song_type %></td>
        <td><%= link_to 'Edit', edit_service_song_type_path(service_song_type) %></td>
        <td><%= link_to 'Destroy', service_song_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Song Type', new_service_song_type_path %>

app/views/service_song_types/new.html.erb
<h1>New Service Song Type</h1>

<%= render 'form', service_song_type: @service_song_type %>

<%= link_to 'Back', service_song_types_path %>

app/views/service_song_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_song_type.name %>
</p>

<%= link_to 'Edit', edit_service_song_type_path(@service_song_type) %> |
<%= link_to 'Back', service_song_types_path %>