config/routes.rb
Rails.application.routes.draw do
  resources :service_song_types
  resources :specials
  resources :singers
  resources :service_songs
  resources :services
  resources :service_types
  resources :songs
  resources :hymn_books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hymn_book.rb
class HymnBook < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :service_type

  has_many :service_songs
  has_many :songs, through: :service_songs
  has_many :specials
  
  def label
    "#{service_type.name} - #{date}"
  end
end

app/models/service_song.rb
class ServiceSong < ApplicationRecord
  belongs_to :service
  belongs_to :song
  belongs_to :service_song_type

  include RailsSortable::Model
  set_sortable :sort
end

app/models/service_song_type.rb
class ServiceSongType < ApplicationRecord
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
end

app/models/singer.rb
class Singer < ApplicationRecord
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :hymn_book
  validates :page_number, uniqueness: { scope: :hymn_book }
end

app/models/special.rb
class Special < ApplicationRecord
  belongs_to :service
  belongs_to :singer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order(:page_number).all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :page_number, :hymn_book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hymn_books_helper.rb
module HymnBooksHelper
end

app/helpers/service_songs_helper.rb
module ServiceSongsHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Hymns</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Hymn Books', hymn_books_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Songs', songs_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Service Types', service_types_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Services', services_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Services Songs', service_songs_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Singers', singers_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Specials', specials_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Service Song Types', service_song_types_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hymns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <div class='container'>
      <% if notice %>
        <div class='row mt-3'>
        <div class='col col-xs-12 alert alert-primary'><%= notice %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>